#!/bin/sh

# Define aliases
rc=riverctl
rt=riverdeck
mod=Super

$rc map-switch normal lid open spawn 'sh ~/.local/bin/monitor-wl.sh'
$rc map-switch normal lid close spawn 'sh ~/.local/bin/monitor-wl.sh'

# Screensharing
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

# Autoload
$rc spawn 'synchting --no-browser >> /dev/null'
$rc spawn 'sh ~/.local/bin/monitor-wl.sh'
$rc spawn 'mpd'
$rc spawn 'mpd-mpris'
$rc spawn 'playerctld'
$rc spawn 'dunst'
$rc spawn 'swaybg -m fill -i ~/Pictures/wallpapers/White-Mountain.jpg'
$rc spawn 'slstatus -s | dam'
$rc spawn 'clipcatd'

# Hardware config

# Mouse
$rc input pointer-1133-16478-Logitech_M720_Triathlon accel-profile flat

# Touchpad
$rc input pointer-1267-12809-ELAN067D:00_04F3:3209_Touchpad accel-profile flat
$rc input pointer-1267-12809-ELAN067D:00_04F3:3209_Touchpad tap enabled
$rc input pointer-1267-12809-ELAN067D:00_04F3:3209_Touchpad middle-emulation enabled

# Trackpoint
$rc input pointer-2-10-TPPS/2_JYT_Synaptics_TrackPoint accel-profile flat


# Floated Windows 
$rc rule-add -app-id 'foot*' -title 'pulsemixer' float
$rc rule-add -app-id 'foot*' -title 'youtube-launcher' float
$rc rule-add -app-id 'foot*' -title 'youtube-downloader' float
$rc rule-add -app-id 'thunar*' float
$rc rule-add -app-id 'imv*' float
$rc rule-add -app-id 'MuPDF*' float
$rc rule-add -app-id 'gimp-file-open*' float
$rc rule-add -app-id 'dialog*' float

# General Config

$rc set-cursor-warp on-focus-change
$rc focus-follows-cursor always

$rc map-pointer normal $mod BTN_LEFT move-view
$rc map-pointer normal $mod BTN_RIGHT resize-view

# Border 
$rc border-width 2
$rc border-color-focused 0xd79920ff
$rc border-color-unfocused 0xd79920AA

# Tiling Layout
$rc default-layout riverdeck
$rt -inner-gaps 2 -per-tag -no-smart-gaps &

# Keyboard Config
$rc keyboard-layout -options "caps:escape" us
$rc set-repeat 50 250

# Bindings

# WM Bindings
$rc map normal $mod+Shift Q exit
$rc map normal $mod+Shift C close
$rc map normal $mod J focus-view next
$rc map normal $mod K focus-view previous
$rc map normal $mod+Shift J swap next
$rc map normal $mod+Shift K swap previous
$rc map normal $mod Return zoom 

# Layout Bindings
riverctl map normal $mod t send-layout-cmd riverdeck "main-location-cycle left,monocle"
riverctl map normal $mod M send-layout-cmd riverdeck "main-location monocle"
riverctl map normal $mod g send-layout-cmd riverdeck "main-location grid"


# Master resize
$rc map normal $mod H send-layout-cmd $rt "main-ratio -0.05"
$rc map normal $mod L send-layout-cmd $rt "main-ratio +0.05"


# Floating window controls
$rc map normal $mod Space toggle-float

# Resize move floating
$rc map normal $mod+Alt H move left 50
$rc map normal $mod+Alt J move down 50
$rc map normal $mod+Alt K move up 50
$rc map normal $mod+Alt L move right 50

# Resize move floating
$rc map normal $mod+Control H resize horizontal -50
$rc map normal $mod+Control J resize vertical 50
$rc map normal $mod+Control K resize vertical -50
$rc map normal $mod+Control L resize horizontal 50


# Fullscreen
$rc map normal $mod+Shift F toggle-fullscreen


# Tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    # $mod+[1-9] focus tags
    $rc map normal $mod $i set-focused-tags $tags

    # $mod+Shift+[1-9] move window to desired tags
    $rc map normal $mod+Shift $i set-view-tags $tags

    # $mod+Control+[1-9] toggle focus of a tag
    $rc map normal $mod+Control $i toggle-focused-tags $tags

    # $mod+Shift+Control+[1-9] focus window on specific tag
    $rc map normal $mod+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
# Focus all tags
$rc map normal $mod 0 set-focused-tags $all_tags

# Move window to all tags
$rc map normal $mod+Shift 0 set-view-tags $all_tags

# Focus last used tag
$rc map normal $mod tab focus-previous-tags

# Personal Bindings
$rc map normal $mod+Shift Return spawn foot
$rc map normal $mod p spawn 'mew-run -i'
$rc map normal $mod+Shift b spawn firefox
$rc map normal $mod e spawn 'foot -e lf'
$rc map normal $mod+Shift m  spawn 'foot -e ncmpcpp'
$rc map normal $mod n spawn 'foot -e newsraft'
$rc map normal $mod+Shift t spawn 'foot -e htop'
$rc map normal $mod u spawn 'foot -T pulsemixer -e pulsemixer'
$rc map normal $mod u spawn 'foot -T pulsemixer -e pulsemixer'
$rc map normal $mod y spawn 'foot -T youtube-launcher -e ~/.local/bin/yt-launcher.sh'
$rc map normal $mod+Shift y spawn 'foot -T youtube-downloader -e ~/.local/bin/yt-downloader.sh'

# Clipboard
$rc map normal $mod v spawn 'clipcat-menu -f custom'
$rc map normal $mod+Shift v spawn 'clipcatctl clear'

# Screenshot
$rc map normal $mod z spawn 'slurp | grim -g - - | tee ~/Pictures/Screenshots/Screenshot-$(date +%Y-%m-%d-%s).png ; notify-send "Screenshot taken."'
$rc map normal $mod+Shift z spawn 'grim ~/Pictures/Screenshots/Screenshot-$(date +%Y-%m-%d-%s).png ; notify-send "Screenshot taken."'

# Brightness
$rc map normal None XF86MonBrightnessUp spawn "bash ~/.local/bin/brightness.sh up"
$rc map normal None XF86MonBrightnessDown spawn "bash ~/.local/bin/brightness.sh down"

# Volume
$rc map normal $mod w spawn 'bash ~/.local/bin/volume.sh up'
$rc map normal $mod s spawn 'bash ~/.local/bin/volume.sh down'
$rc map normal $mod+Shift s spawn 'bash ~/.local/bin/volume.sh mute'
$rc map normal None XF86AudioRaiseVolume  spawn "bash ~/.local/bin/volume.sh up" 
$rc map normal None XF86AudioLowerVolume  spawn "bash ~/.local/bin/volume.sh down" 
$rc map normal None XF86AudioMute         spawn "bash ~/.local/bin/volume.sh mute"
$rc map normal $mod o spawn "pactl set-default-sink alsa_output.usb-HP_HP_Speaker_Bar-00.analog-stereo ; notify-send -t 8000 Output: Speaker"
$rc map normal $mod+Shift o  spawn "pactl set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo ; notify-send -t 8000 Output: Headphones"
$rc map normal $mod b spawn 'pgrep dam && killall dam || slstatus -s | dam'

# Media Control
$rc map normal $mod backslash spawn 'playerctl play-pause'
$rc map normal $mod bracketright spawn 'playerctl next'
$rc map normal $mod bracketleft spawn 'playerctl previous'
