# Gruvbox Theming

[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# Transparency
[window]
opacity = 0.95

# Font config
[font]
normal.family = "LiterationMono  Nerd Font"
bold.family = " LiterationMonoNerd Font"
italic.family = "LiterationMono Nerd Font"
bold_italic.family = "LiterationMono Nerd Font"

size = 10.5

# Add bindings
[keyboard]
bindings = [
    { key="ArrowUp", mods="Control|Shift", action="ScrollLineUp" },
    { key="ArrowDown", mods="Control|Shift", action="ScrollLineDown" },
    { key="Home", mods="Control|Shift", action="ScrollPageUp" },
    { key="End", mods="Control|Shift", action="ScrollPageDown" },
    { key="k", mods="Control|Shift", action="ScrollLineUp" },
    { key="j", mods="Control|Shift", action="ScrollLineDown" },
]
